### PR TITLE
add slack link to chat page

### PR DESCRIPTION
**Pull request by somlor**
@tobias a bunch of us have been hanging out on a dedicated slack account for asheville coder's league. 

at the request of señor @wukkuan this commit adds a link to /chat.html page to join our slack group.

the join link goes to slack.avlcoders.org, so this first requires you to add a CNAME for slack.avlcoders.org pointing to slack-avlcoders.herokuapp.com.

### CODE REVIEW

**Comment by tobias** [comment]
I don't have rights to change the dns, I believe @semmypurewal owns the domain. What is the purpose of the heroku app? Can we not point directly to avlcoders.slack.com?

**Comment by somlor** [comment]
@tobias that heroku link is a simple app @wukkan pointed out to me called [slackin](http://rauchg.com/slackin/) that creates a signup page. i guess this is not something slack themselves provide.

**Comment by wukkuan** [comment]
Slack doesn't give us the ability to just let anyone join who wants. Instead, admins have to manually invite everyone.

**Comment by tobias** [comment]
Gotcha. Would you be willing to change that link to the herokuapp url for now? I can then go ahead and merge that in while we wait for possible dns changes.

**Comment by semmypurewal** [comment]
Hey folks, yeah I can do the DNS change. I'll add it to my to-do list for this weekend.

**Comment by tobias** [comment]
Great, thanks @semmypurewal.

**Comment by somlor** [comment]
@tobias ok i just pushed another commit to use heroku url. up to you if you want to just wait for dns change.

**Comment by bhauman** [comment]
is there currently and irc channel?

**Comment by tobias** [comment]
@bhauman - yes, #avlcoders on freenode.

**Comment by tobias** [comment]
@somlor - I'll go ahead and merge to take any pressure off of @semmypurewal (no rush, Semmy!)

**Comment by semmypurewal** [comment]
Just added the CNAME record, will probably take awhile to be updated. Let me know if it doesn't work in a day or so.

**Comment by tobias** [comment]
Thanks @semmypurewal, it's working for me. @somlor - I changed the page to point to slack.avlcoders.org

**Comment by somlor** [comment]
@semmypurewal @tobias sweetness. thx! :+1:

**Comment by semmypurewal** [comment]
@somlor @tobias @wukkuan FYI:

http://slackhq.com/post/114696167740/march-2015-security-incident-and-launch-of-2fa

**Comment by tobias** [comment]
Thanks Semmy. I have another Slack account that was affected by this
breach. It's a good reminder to not share passwords between accounts.

**Pull request merged**
